Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.8.1/libexec/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/main.py", line 712, in main
    "--strict-permissions" in cli_args)
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/util.py", line 108, in make_or_verify_dir
    os.makedirs(directory, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt'
